language = {
    'en': {
        'welcome_title': 'BiliMusicCLI v2.0.0',
        'welcome_subtitle': 'Bilibili Audio Downloader & Voice Music Assistant',
        'welcome_author': 'Author: Mr.Li',
        'features_title': 'Features:',
        'features': [
            '• Download Bilibili video audio (saved as .m4s)',
            '• Voice command music playback (wake words: 小爱同学 / 播放)',
            '• Local cache with auto-playlist and version switching',
            '• Console commands: help, download, voice, exit, etc.'
        ],
        'getting_started': 'Getting started: type \'help\' or say \'小爱同学播放<歌名>\'',

        'cmd_exit_brief': 'Exit',
        'cmd_transform_brief': 'Convert a file',
        'cmd_help_brief': 'Show help',
        'cmd_download_brief': 'Download by URL',
        'cmd_voice_brief': 'Voice control',
        'cmd_cache_brief': 'Cache management',
        'cmd_search_brief': 'Manually search and play a song',
        'cmd_reconnect_brief':'Reconnect micro:bit',
        'cmd_batch_transform_brief': 'Batch convert to MP3',
        'cmd_batch_search_brief':'Batch download .m4s from a text file (no conversion)',
        'cmd_batch_extract_brief':'Batch download and convert to MP3 (auto-cleanup .m4s files)',
        'cmd_pause_brief':'Pause the current song',

        'cmd_exit_usage': 'exit\n    Exit the program.',
        'cmd_transform_usage': 'transform\n    Convert a single audio/video file via GUI selection.',
        'cmd_help_usage': 'help [command]\n    Show usage of built-in commands.',
        'cmd_download_usage': 'download <URL1> [URL2] ...\n    Download one or multiple Bilibili audio streams by URL.\n    URL must start with https://www.bilibili.com/video/BV...',
        'cmd_voice_usage': 'voice\n    Start continuous voice recognition for song requests.\n    Wake words: 小爱同学 / 播放',
        'cmd_cache_usage': 'cache list | clean [bvid]\n    Manage song cache: list all or clean by bvid.',
        'cmd_search_usage':'"search <song_name> [<singer>]"',
        'cmd_reconnect_usage':'reconnect\n    Try to reconnect micro:bit.',
        'cmd_batch_transform_usage': 'batch_transform [folder]\n    Batch convert all supported audio/video files in a folder to MP3.\n    If no folder is given, a folder selection dialog will appear.',
        'cmd_batch_search_usage': 'batch_search\n    Select a text file with song names/URLs,\n    download each as .m4s (kept in m4s_temp/).',
        'cmd_batch_extract_usage':'batch_extract [file]\n    Select or provide a text file with song names/URLs,\n    download and convert each to MP3, then delete .m4s.',
        'cmd_pause_usage': 'pause',

        'press_enter': 'Press Enter to continue...',
        'unknown_command': 'Unknown command: {}',
        'available_commands': 'Available commands:',
        'type_help': "Type 'help <command>' for detailed usage.",
        'no_detailed_help': "No detailed help for command '{}'.",
        'invalid_choice': 'Invalid selection: {}, please try again',
        'please_enter': ' >? ',
        'press_ctrl_c': 'Press Ctrl+C to stop',
        'voice_already_running': 'Voice recognition already running.',
        'loading_voice_model': 'Loading voice model, please wait...',
        'voice_ready': 'Voice recognition ready, please speak...',
        'voice_interrupted': 'Voice recognition interrupted by user.',
        'voice_exited': 'Voice recognition exited.',
        'playback_finished': '\n[Playback finished]',
        'now_playing': 'Now playing: {}',
        'playback_paused': 'Playback paused',
        'playback_resumed': 'Playback resumed',
        'playback_stopped': 'Playback stopped',
        'no_cached_songs': 'No cached songs, cannot auto-play next.',
        'auto_playing_next': 'Auto-playing next: {}',
        'cache_hit': 'Cache hit: {}, playing directly.',
        'cache_file_missing': 'Cache file missing: {}, will re-download.',
        'downloading': 'Downloading: {} ({})',
        'download_success': '✓ Download successful -> {}',
        'download_failed': '✗ Download failed: {}',
        'downloaded_file_not_found': 'Downloaded file not found: {}',
        'no_matching_song': 'No matching song found.',
        'error_processing_song': 'Error processing song: {}',
        'switching_to_version': 'Switching to version: {}',
        'no_other_versions': 'No other versions available.',
        'cache_empty': 'Cache is empty.',
        'cached_songs': 'Cached songs:',
        'file_label': 'File: {}',
        'delete_all_cache': 'Delete all cache files and records? (y/N): ',
        'cancelled': 'Cancelled.',
        'all_cache_cleared': 'All cache cleared.',
        'cache_cleared_for': 'Cache cleared for: {}',
        'cache_not_found': 'Cache not found: {}',
        'invalid_subcommand': 'Unknown subcommand, available: list, clean',
        'conversion_failed': 'ffmpeg conversion failed, error code {}',
        'user_cancelled': 'User cancelled.',
        'select_file_title': 'Select file to convert:',
        'video_file_label': 'Video File',
        'audio_file_label': 'Audio File',
        'select_folder_title': 'Select folder to batch convert',
        'invalid_folder': 'Invalid folder: {}',
        'no_files_found': 'No supported media files found in {}',
        'skip_existing_mp3': 'Skipping existing MP3: {}',
        'converting': 'Converting: {} -> {}',
        'conversion_successful': 'Conversion successful: {}',
        'batch_failed':'  ✗ Failed: {}',
        'batch_done': 'Batch conversion done, {}/{} succeeded.',
        'usage_download': 'Usage: download <URL1> [URL2] ...\nURL must start with https://www.bilibili.com/video/BV...',
        'warning_invalid_urls': 'Warning: invalid URLs skipped:',
        'no_valid_urls': 'No valid Bilibili URLs provided.',
        'unexpected_error': 'Unexpected error: {}, details written to error.log',
        'initialization_done_restart': 'Initialization complete, please restart manually to apply configuration...',
        'warning_mpv_dll': 'Warning: libmpv-2.dll not found, please put it in bin/ folder.',
        'mpv_player_initialized': 'mpv player initialized successfully',
        'voice_recognition_thread_error': 'Voice recognition thread error: {}',
        'voice_recognition_interrupted':'\nVoice recognition interrupted by user.',
        'voice_recognition_error': 'Voice recognition error: {}',
        'worker_thread_error': 'Worker thread error: {}',
        'recognition_error': 'Recognition error: {}',
        'cleanup_done': 'The program has finished running, and the resources it occupied have been released.',
        'switching_to_next_song':'Switching to next song manually.',
        'cache_usage':'Usage: cache list | clean [bvid]',
        'no_files_to_convert': 'No files to convert.',
        'search_usage':'Usage: search <song_name> [singer]',
        'searching_for': 'Searching for: {}',
        'batch_search_start': 'Found {} songs. Starting batch search...',
        'microbit_port_not_configured':'❌ micro:bit port not configured. Please run initialization again.',
        'microbit_reconnecting':'🔄 Attempting to reconnect to micro:bit...',
        'processing_item': '--- Processing {}/{}: {} ---',
        'detected_url_downloading': 'Detected Bilibili URL, downloading directly.',
        'download_finished': 'Download finished.',
        'invalid_input_yns': 'Invalid input. Please enter y, n or s.',
        'prompt_auto_mode': 'Auto mode? (y: auto download best, n: manual select, s: skip this): ',
        'processing_entries': 'Processing {} entries...',
        'skipping_conversion':'  ✗ Download failed, skipping conversion.',
        'already_mp3_skip': '  → Already exists as MP3, skipping conversion.',
        'converted_to_mp3': '  → Converted to MP3.',
        'batch_extract_failed':'  ✗ Failed: {}: {}',
        'mic_invalid_reconfig': 'The microphone device is invalid or not set up, will reconfigure...',
        'pyserial_not_installed':'pyserial not installed, micro:bit control disabled.',
        'microbit_connected':'✅ micro:bit connected on {}',
        'microbit_error':'⚠️ micro:bit error: {}',
        'prompt_play_now': 'Play now? (y/n): ',
        'saving_to_directory': 'Converted MP3 files will be saved to: {}',
    },
    'zh': {
        'welcome_title': 'BiliMusicCLI v2.0.0',
        'welcome_subtitle': '哔哩哔哩音频下载 & 语音点歌助手',
        'welcome_author': '作者：Mr.Li',
        'features_title': '功能：',
        'features': [
            '• 下载 Bilibili 视频音频（保存为 .m4s）',
            '• 语音指令点歌（唤醒词：小爱同学 / 播放）',
            '• 本地缓存，自动联播，版本切换',
            '• 控制台命令：help, download, voice, exit 等'
        ],
        'getting_started': "开始：输入 'help' 查看命令，或说 '小爱同学播放<歌名>'",

        'cmd_exit_brief': '退出程序',
        'cmd_transform_brief': '转换文件',
        'cmd_help_brief': '显示帮助',
        'cmd_download_brief': '通过链接下载',
        'cmd_voice_brief': '语音点歌',
        'cmd_cache_brief': '缓存管理',
        'cmd_search_brief': '手动搜索并播放歌曲',
        'cmd_reconnect_brief':'手动重连micro:bit',
        'cmd_batch_transform_brief': '批量转换为 MP3',
        'cmd_batch_search_brief': '批量下载 .m4s（不转换）',
        'cmd_batch_extract_brief': '批量下载并转换为 MP3（自动清理 .m4s）',
        'cmd_pause_brief': '暂停当前歌曲',

        'cmd_exit_usage': 'exit\n    退出控制台程序。',
        'cmd_transform_usage': 'transform\n    通过图形界面选择文件，转换为 MP3。',
        'cmd_help_usage': 'help [命令名]\n    显示内置命令的帮助信息。',
        'cmd_download_usage': 'download <URL1> [URL2] ...\n    下载一个或多个 B 站音频流。\n    URL 必须以 https://www.bilibili.com/video/BV... 开头。',
        'cmd_voice_usage': 'voice\n    启动连续语音识别点歌。\n    唤醒词：小爱同学 / 播放',
        'cmd_cache_usage': 'cache list | clean [bvid]\n    管理缓存：列出全部或按 BV 号清理。',
        'cmd_search_usage': 'search <歌名> [<歌手>]\n    手动搜索歌曲并交互式选择播放。',
        'cmd_reconnect_usage':'reconnect\n    尝试重连micro:bit',
        'cmd_batch_transform_usage': 'batch_transform [文件夹路径]\n    批量转换文件夹内所有支持的音视频文件为 MP3。\n    若不指定文件夹，则弹出选择对话框。',
        'cmd_batch_search_usage': 'batch_search\n    选择包含歌名或链接的文本文件，\n    批量下载为 .m4s（保留在 m4s_temp/ 目录）。',
        'cmd_batch_extract_usage': 'batch_extract [文件]\n    选择或指定包含歌名或链接的文本文件，\n    下载并转换为 MP3，然后删除原 .m4s 文件。',
        'cmd_pause_usage': 'pause\n    暂停或继续当前播放。',

        'microbit_port_not_configured': '❌ 未配置 micro:bit 端口，请重新运行初始化。',
        'microbit_reconnecting': '🔄 正在尝试重连 micro:bit...',
        'pyserial_not_installed': '未安装 pyserial，micro:bit 控制功能已禁用。',
        'microbit_connected': '✅ micro:bit 已连接到 {}',
        'microbit_error': '⚠️ micro:bit 错误：{}',
        'batch_failed': '  ✗ 失败：{}',
        'batch_extract_failed': '  ✗ 失败：{}：{}',
        'skipping_conversion': '  ✗ 下载失败，跳过转换。',
        'search_usage': 'search <歌名> [<歌手>]\n    手动搜索歌曲并交互式选择播放。',
        'voice_recognition_interrupted': '\n用户中断了语音识别',

        'press_enter': '按回车键继续...',
        'unknown_command': '未知命令：{}',
        'available_commands': '可用命令：',
        'type_help': '输入 \'help <命令>\' 查看详细用法',
        'no_detailed_help': '命令 {} 没有详细帮助信息',
        'invalid_choice': '无效选择：{}，请重试',
        'please_enter': ' >? ',
        'press_ctrl_c': '按 Ctrl+C 停止',
        'voice_already_running': '语音识别已在运行中。',
        'loading_voice_model': '正在加载语音模型，请稍候...',
        'voice_ready': '语音识别已就绪，请说话...',
        'voice_interrupted': '用户中断语音识别',
        'voice_exited': '语音识别已退出',
        'playback_finished': '[播放结束]',
        'now_playing': '正在播放：{}',
        'playback_paused': '播放已暂停',
        'playback_resumed': '播放已继续',
        'playback_stopped': '播放已停止',
        'no_cached_songs': '缓存中没有歌曲，无法自动联播',
        'auto_playing_next': '自动联播下一首：{}',
        'cache_hit': '发现缓存：{}，直接播放。',
        'cache_file_missing': '缓存文件丢失：{}，将重新下载。',
        'downloading': '下载视频：{} ({})',
        'download_success': '✓ 下载成功！保存至: {}',
        'download_failed': '✗ 下载失败：{}',
        'downloaded_file_not_found': '下载的文件未找到：{}',
        'no_matching_song': '未找到相关歌曲。',
        'error_processing_song': '处理歌曲时出错：{}',
        'switching_to_version': '切换到下一版本：{}',
        'no_other_versions': '没有其他版本可切换',
        'cache_empty': '缓存为空。',
        'cached_songs': '缓存的歌曲：',
        'file_label': '文件：{}',
        'delete_all_cache': '确认删除所有缓存文件与记录？(y/N): ',
        'cancelled': '取消。',
        'all_cache_cleared': '所有缓存已清除。',
        'cache_cleared_for': '已清除缓存：{}',
        'cache_not_found': '未找到缓存：{}',
        'invalid_subcommand': '未知子命令，可用: list, clean',
        'conversion_failed': 'ffmpeg 转换失败，错误码 {}',
        'user_cancelled': '用户取消了选择。',
        'select_file_title': '请选择需转换的文件：',
        'video_file_label': '视频文件',
        'audio_file_label': '音频文件',
        'select_folder_title': '请选择要转换的文件夹',
        'invalid_folder': '无效的文件夹：{}',
        'no_files_found': '在 {} 中没有找到支持的音视频文件',
        'skip_existing_mp3': '跳过已存在的 MP3：{}',
        'converting': '转换：{} -> {}',
        'conversion_successful': '转换成功：{}',
        'batch_done': '批量转换完成，成功 {}/{} 个文件',
        'usage_download': '用法：download <URL1> [URL2] ...\n提示：URL 必须为 https://www.bilibili.com/video/BVxxxx... 格式',
        'warning_invalid_urls': '警告：以下链接格式不正确，已跳过：',
        'no_valid_urls': '没有有效的 Bilibili 链接，下载已取消。',
        'unexpected_error': '程序发生未预期错误：{}，详情已写入 error.log',
        'initialization_done_restart': '初始化已完成，请手动重启使配置生效...',
        'warning_mpv_dll': '警告: 未找到 libmpv-2.dll，请将其放入 bin/ 文件夹或项目根目录',
        'mpv_player_initialized': 'mpv 播放器初始化成功',
        'voice_recognition_thread_error': '语音识别线程出错：{}',
        'voice_recognition_error': '语音识别错误：{}',
        'worker_thread_error': '工作线程错误：{}',
        'recognition_error': '识别错误：{}',
        'cleanup_done': '程序已运行完毕，所占资源已被释放。',
                'no_files_to_convert': '没有需要转换的文件。',
        'searching_for': '正在搜索：{}',
        'batch_search_start': '共 {} 首歌曲，开始批量搜索...',
        'processing_item': '--- 处理第 {}/{} 项：{} ---',
        'detected_url_downloading': '检测到 Bilibili 链接，直接下载。',
        'download_finished': '下载完成。',
        'invalid_input_yns': '输入无效，请输入 y、n 或 s。',
        'prompt_auto_mode': '自动模式？(y: 自动下载最佳结果, n: 手动选择, s: 跳过该项): ',
        'processing_entries': '处理 {} 个条目...',
        'already_mp3_skip': '  → 已存在 MP3，跳过转换。',
        'converted_to_mp3': '  → 已转换为 MP3。',
        'mic_invalid_reconfig': '麦克风设备无效或未配置，即将重新配置...',
        'prompt_play_now': '立即播放？(y/n): ',
        'saving_to_directory': '转换后的 MP3 将保存至：{}',
    }
}
